### ISSUE TITLE
limit duration of search session

### ISSUE THREAD

**Issue by harrisonpim** [wellcomecollection/reporting#50]
follows https://github.com/wellcomecollection/wellcomecollection.org/issues/4110 and https://github.com/wellcomecollection/wellcomecollection.org/issues/4149

Currently, we see some `anonymousID`'s search sessions spanning multiple days. To improve our analysis, we want to update our definition of a session, limiting them to a continued period of activity on the site (ie a session finishes after ~30 mins inactivity).

NB this represents a significant change to our data collection methodology and the date that this starts running on the site should be recorded in gitbook.

---

## Solution

We will add a field `sessionId` when there is a gap between events of 30minutes+

**Comment by taceybadgerbrook** [comment]
I like the idea of creating a sessionId field. This means we could evaluate conversion wrt to session. 

I also like the idea of keeping anonymousId. This avoids discontinuity over time with dashboard stats like views per unique workId (calculated by cardinality:anonymousId)

**Comment by taceybadgerbrook** [comment]
Thanks for adding the Data Analysis label, too. One day I'll crack using Github...

**Comment by jamesgorrie** [comment]
Done https://github.com/wellcomecollection/wellcomecollection.org/pull/5960
