### ISSUE TITLE
Additional mappings for metrics-conversion-prod

### ISSUE THREAD

**Issue by taceybadgerbrook** [wellcomecollection/reporting#87]
The following fields cannot be used in Kibana dashboard aggregations because they are not of type keyword. Text doesn't appear to allow counts.

|field|Used to count|
|:---|:---|
|page.query.query|queries with null results, popular queries|
|page.query.workId|popular items viewed|
|page.query.id|archive works pages viewed|

**Comment by harrisonpim** [comment]
first, we want to:

- add `workId`
- add `id` (this is the image id. This comes from the querystring parameters, so could be used in multiple places)
- add `.keyword` to `query.query`, alongside its existing `text` value

later, we'll 
- change the `source` field from text to keyword
- change the `queryType` field from text to keyword

**Comment by taceybadgerbrook** [comment]
@jamesgorrie @harrisonpim median click position is the 50th percentile for page.query.resultPosition but this field is not a number.

Is median click position still useful to measure search? Could this field be changed to a number?

**Comment by jamesgorrie** [comment]
@taceybadgerbrook we have added `id` to the mapping, we are now populating the data.

e.g.
```JSON
GET metrics-conversion-prod/_search
{
  "size": 0,
  "aggs": {
    "id": {
      "terms": {
        "field": "page.query.id",
        "size": 10
      }
    }
  }
}
```
