### ISSUE TITLE
Item page reporting behaviour is incorrect

### ISSUE THREAD

**Issue by jamieparkinson** [wellcomecollection/reporting#99]
I haven't had time to look into this properly but I can see some oddities in both the dashboards and the tracking events themselves.

### Dashboards
The visualizations in the Collections dashboard in the reporting cluster use the following query over the conversion index:
```
(page.name:item or page.name:images) AND page.pathname: /item AND NOT (source:viewer/paginator)
```
This doesn't seem quite right to me: doesn't the `page.pathname: /item` filter exclude all `images` pages? Do we know if we want to exclude item views that come from image search?

### Events/tracking
A page load on `/works/{id}/items` gives us an event with `name: 'item'`: see https://github.com/wellcometrust/wellcomecollection.org/blob/ec0adb1246475c0ea1513e830fb24a030237449c/catalogue/webapp/pages/item.tsx#L357

However, when we click through _from a works search_ to an item page (rather than loading it directly), the tracking event (seen in the Network tab in Chrome dev tools has `name: 'works'`!:
```
{  
  path: "/works/jzgdbvcm/items",
  pathname: "/item",
  name: "works",
  query: {workId: "jzgdbvcm"}
}
```
I'm not sure why this is, but it seems likely that it explains inconsistencies in the items reporting data.

**Comment by taceybadgerbrook** [comment]
@jamieparkinson I'll have a look at what I can see when I view and item from the catalogue and then from images later on today.

**Comment by jamieparkinson** [comment]
It does seem like there's something up with `page.name` being consistently correct - I think for now your best bet might be to ignore it and just to use `pathname` for everything?

**Comment by taceybadgerbrook** [comment]
This could come back to bite me. What happens if we decide to treat all images as if they were all item views of works?

**Comment by taceybadgerbrook** [comment]
I don't mind using pathname over page.name as longer as it doesn't change. I'm racking my brains as to why my definition is wrong.

**Comment by jamieparkinson** [comment]
> What happens if we decide to treat all images as if they were all item views of works?
I think we can probably think of issues on either side of whether we're using `page.name` or `pathname`, so that wouldn't be a major concern.

What do you mean by your definition being "wrong"? I don't see a problem with it per se, but pragmatically we know there's a data issue here so we should choose a query that sidesteps it - so if you change your query to be `page.pathname: /item AND NOT (source:viewer/paginator)`, that might get us there?

**Comment by taceybadgerbrook** [comment]
I think it's important to include page.pathname because the path (ie catalogue or images) determines the value of page.name. I have updated all Kibana visualisations, ticket #8437, and [Notion page ](https://www.notion.so/wellcometrust/Kibana-dashboard-definitions-4eb8af16a00b4f81955015696d9c25a3)with the new definition:

((page.name:work) AND page.pathname:/item AND NOT (source:viewer/paginator)) or ((page.name:images) AND page.pathname:/image )
